<?php

namespace App\Auth\Security\Exception;

use Symfony\Component\Security\Core\Exception\AccountStatusException;
use App\User\Model\UserInterface;

/**
 * AccountBanned is thrown when the user account is banned.
 */
final class AccountBanned extends AccountStatusException
{
    public function getMessageKey()
    {
        return 'account.banned';
    }

    public function getMessageData()
    {
        return parent::getMessageData(); // TODO: Change the autogenerated stub
    }
}
